# Generated by Django 3.1.1 on 2020-10-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('art_no', models.CharField(default='', max_length=50)),
                ('colors', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='', upload_to='srtextile/images')),
            ],
        ),
    ]
