# Generated by Django 3.1.1 on 2020-10-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srtextile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric_logo',
            field=models.ImageField(default='', upload_to='srtextile/images'),
        ),
    ]
